@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

' Standard configuration for compatibility
set separator none

title Container Diagram

' External Systems
Person_Ext(partner, "Partner", "External system that transmits data to the company's system")
System_Ext(ssn_service, "SSN Service", "Service with the ability to verify identity by SSN")

' System Boundary
System_Boundary(cms_boundary, "Application Processing Platform") {
    
    Container(crm, "Monolithic CRM System (UI + crmend)", "Software System", "System for managing and enters applications,contacts, contracts, and customer profiles")
    Container(validation_service, "Application Normalization and Validation Service", "Software System", "Normalizes and validates applications to prevent duplicates in the system")
    Container(db, "Database", "Postgres","Storage of normalized and validated data")
    Container(mongo, "Raw Applications Store", "MongoDB","Database for store non-normalized applications")
}

Person(employee, "Company Employee", "Communicates with the client. Enters applications into the system")

' Relationships
Rel(crm, employee, "Retrieve client data for communication, verification, and duplicate confirmation")
Rel(employee, crm, "Creation and management of applications, retrieval of client data, and client verification")
Rel(crm, mongo, "Makes API calls", "JSON/HTTP")
Rel(mongo,validation_service, "Makes API calls", "JSON/HTTP")
Rel(validation_service, db,"Store processed data","")
Rel(crm, ssn_service, "Makes API calls", "JSON/HTTP")
Rel(partner, validation_service, "Makes API calls", "JSON/HTTP")
@enduml